name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  default:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    runs-on: ${{ matrix.os }}
    name: default ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: read-yaml
        with:
            config: config.yaml
      - run: |
          echo ${{ steps.read-yaml.outputs['some-key.value'] }}
